### ISSUE TITLE
Add instance namespacing to Barista configuration

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#327]
Barista instances should take a list of acceptable namespaces that it will pass along for.

The questions here are: are namespaces implicit or explicit arguments and should a single barista instance handle more than one namespace?

Thinking, I think the best solution is permissions like:
```yaml
    noctua-go:
      allow-edit: true
    noctua-monarch:
      allow-admin: true
```
And use the context variable as a first pass to tag onto the "noctua-" string.

Current namespaces may be "go", "monarch", and "open".

**Comment by kltm** [comment]
The sooner we make this change, or whatever similar change, the better--we've begun to seriously overload the GO users.yaml.

**Comment by kltm** [comment]
Actually, maybe:
```yaml
 authorizations:
    noctua:
       go:
         allow-edit: true
       monarch:
         allow-admin: true
```
no need for mapping. Not backwards compatible, but makes more sense.
