### ISSUE TITLE
Implement simple client-side reasoner for domain-range checks

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#358]
cc @dosumis @balhoff 

As discussed here https://docs.google.com/document/d/1gzdOjmQn34-A2EUJuujoMzVrAZr0RZfofCVjxW3msZU/edit 
I will implement a fast js implementation that performs incomplete checks for domain-range constraints (and possibly AllValuesFrom). It will complement a complete server-side reasoner and be used for things like #165 

It will be initiated with an obograph-json of RO

Input will be a tuple `(subject-closure, object-closure)`. It will return a list of valid relations for any two individuals instantiating the respective classes. The client will need to supply closure (which can come from minerva). From this there is also a trivial extra signature with a relation argument that returns true-false.

Formal note: as described this is a closed world inference. It is best conceived of as an open-world reasoner that has a test to see if new entailments are found. E.g. if you say that some Thing occurs in some cell, the inference is the Thing is also a continuant. But the client is free to act on this as being not valid, requiring the user to be sufficiently precise about types

**Comment by kltm** [comment]
The document is not public; could you copy in the relevant portions?

**Comment by cmungall** [comment]
public now

**Comment by cmungall** [comment]
Example of RO axioms:

```
  - predicateId: "http://purl.obolibrary.org/obo/RO_0002207"
    allValuesFromEdges:
    - sub: "http://purl.obolibrary.org/obo/CL_0000000"
      pred: "http://purl.obolibrary.org/obo/RO_0002207"
      obj: "http://purl.obolibrary.org/obo/CL_0000000"
    - sub: "http://purl.obolibrary.org/obo/CARO_0010000"
      pred: "http://purl.obolibrary.org/obo/RO_0002207"
      obj: "http://purl.obolibrary.org/obo/CARO_0010000"
  - predicateId: "http://purl.obolibrary.org/obo/RO_0002009"
    domainClassIds:
    - "http://purl.obolibrary.org/obo/CL_0000000"
  - predicateId: "http://purl.obolibrary.org/obo/RO_0002202"
    domainClassIds:
    - "http://purl.obolibrary.org/obo/BFO_0000004"
    rangeClassIds:
    - "http://purl.obolibrary.org/obo/BFO_0000004"
  - predicateId: "http://purl.obolibrary.org/obo/RO_0002565"
    domainClassIds:
    - "http://purl.obolibrary.org/obo/GO_0040011"
  - predicateId: "http://purl.obolibrary.org/obo/RO_0002204"
    domainClassIds:
    - "http://purl.obolibrary.org/obo/BFO_0000004"
    rangeClassIds:
    - "http://purl.obolibrary.org/obo/BFO_0000002"
  - predicateId: "http://purl.obolibrary.org/obo/RO_0002325"
    domainClassIds:
    - "http://purl.obolibrary.org/obo/BFO_0000040"
    rangeClassIds:
    - "http://purl.obolibrary.org/obo/BFO_0000040"
```
