### ISSUE TITLE
Ability to 'Add component'

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua#419]
Hi,

Considering that there are options to "Add process" and "Add function", why is there no option to "Add component".

I need to add a component just as often as I need to add a process or a function.

It would be really great to be have a template for adding a component. It would be even more great, if the template had two [occurs in] boxes, since I frequently need to add both a cell type and an anatomical structure.

thanks,

-Karen

**Comment by kltm** [comment]
@thomaspd I feel like we had something like this (or at least planned to) at some point, but removed it due to either overhead considerations, or that it was slightly against the annoton-based mindset. Unfortunately, my notes yield little here; would you remember anything?

**Comment by kltm** [comment]
@krchristie Until there is a response from Paul, to explore this a bit more, let me try and get into the details of your use case a little. (pinging @ukemi or @vanaukenk or verification)

Within annoton modeling, cellular component is sometimes an "optional" addition. There may be cases where a CC term needs to be added separately, which would use the "Add individual" functionality. Do you have cases where CC terms are added without MF or BP; do these include an enabled by relation as well?

**Comment by krchristie** [comment]
It seems inconsistent that we templates for have 2 of the 3 aspects of GO, but not the third one. If you can just add an individual for anything that isn't an annoton, why do we have specific options for two of the aspects of GO, but not the third one?

I have lots of cases where I want to add CC info only. I come across many, many papers where all I get for some genes is CC info. Unfortunately (in my opinion) I am forced to link them to anonymous MFs. I can be OK with that, provided I can get my CC annotations out, however, frequently, I don't get out the basic annotations I want.

One of my current examples is this model: PMID-23525783-KRC. I am not getting any CC annotations to the term '9+2 motile cilium'. The annotations I want would include two pieces of extension information, one for the cell type and another for the anatomical term:
* occurs_in 'ependymal cell'
* occurs_in 'lateral ventricle'

**Comment by krchristie** [comment]
Let me add, I would eventually also want to get similar CC annotations to '9+2 motile cilium' for the relevant genes from the model section that is centered around 'trachael epithelial cell' and 'trachea epithelium', but I've been experimenting with the model and don't think that side is connected properly (as of 5/8/17).

**Comment by cmungall** [comment]
Sorry if this is a bit cryptic, on a plane right now with slow 
connection don't have links to hand.

@dosumis has extended the yaml DOSDP framework we use for ontology 
design patterns to individuals. We should add some DPs for components 
following your use case:

```
vars:
  - component: "cell component"
  - cell: "cell"
  - structure: "anatomical structure"

triples:
  text: |
   :1 a %s .
   :2 a %s .
   :3 a %s .
   :1 part_of :2 .
   :2 part_of :3 .
|
  vars:
  - component
  - cell
  - structure
```

(this may not be the precise syntax we agreed on, don't have the ticket 
at hand)

DPs like this will drive the wizards in the left panel

cc @DoctorBud @balhoff

**Comment by dosumis** [comment]
```yaml

classes:
   ...

vars:
  gene_product:  {however we specific gene product)
  function: "molecular_function"
  component: "cell component"
  cell: "cell"
  structure: "anatomical structure"

instance_graph:
    nodes: 
       cc: component
       c: cell
       a:  structure
       gp: gene_product

   triples:
      - [mf, enabled_by, gp]
      - [gp, occurs in cc]
      - [ cc, part_of c]
      - [ c, part_of, a ]
```

json schema spec: [graph](https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/spec/DOSDP_schema_full.yaml#L593); [triples spec](https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/spec/DOSDP_schema_full.yaml#L319)
